"""Verify that Final_Autumn_2026_final.ipynb (41 cells) carries everything in Final_Autumn_2026-1.ipynb (107 cells).

Run from the repository root, after executing the 41-cell notebook:   python3 notes/final41/verify_final41.py
Checks (each prints PASS or the differences):
  1. structure: 41 cells whose types match the exam template (from git commit 174f164); every exam cell is unchanged,
     except the three setup cells, which differ from the template only by the documented _DATA_DIR fallback;
  2. code: every code statement of the 107-cell notebook is present, in order, in the right slot, and nothing else
     is (comments, blank lines and the section-banner prints excepted);
  3. text: every markdown cell of the 107-cell notebook is present; the deliberate corrections are written, as diffs,
     to notes/final41/text_changes.md;
  4. outputs: the outputs of each merged cell equal the outputs of the cells it replaces (timings and the random ids
     in HTML tables excepted; images compared byte for byte);
  5. numbers: every number in the answers and the write-up is printed by some cell (the same coarse rule as
     notes/p3_build/check_numbers.py), and the 41-cell version has no unprinted number the 107-cell version lacked.
"""
import json, re, html, subprocess, difflib, hashlib, sys

OLD, NEW = 'Final_Autumn_2026-1.ipynb', 'Final_Autumn_2026_final.ipynb'
old = json.load(open(OLD))['cells']
new = json.load(open(NEW))['cells']
tmpl = json.loads(subprocess.run(['git', 'show', '174f164:Final_Autumn_2026-1.ipynb'], capture_output=True, text=True, check=True).stdout)['cells']
src = lambda c: ''.join(c['source'])
ok = True
def report(name, problems):
    global ok
    ok &= not problems
    print(f'[{"PASS" if not problems else "FAIL"}] {name}' + ('' if not problems else ':\n  - ' + '\n  - '.join(problems)))

# The layout is re-read from the build script's source (without running it) so both use one definition.
bsrc = open('notes/final41/build_final41.py').read()
ns = {}
exec(bsrc[bsrc.index('P3_SECTIONS = ['):bsrc.index('used = sorted(')], ns)
P3, LAYOUT = ns['P3_SECTIONS'], ns['LAYOUT']
slots = {s: (v if isinstance(v, list) else None) for s, v in LAYOUT.items()}
slots[39] = [i for s in P3 for i in s[3]]
slots[40] = [106] + [s[2] for s in P3]

# ---------------------------------------------------------------- 1. structure
p = []
if len(new) != 41: p.append(f'{len(new)} cells, not 41')
if [c['cell_type'] for c in new] != [c['cell_type'] for c in tmpl]: p.append('cell types differ from the template')
answer_or_code = {s for s, t in enumerate(tmpl) if src(t).strip() in ('**Answer:**', '# Your codes here.', '# Your codes here (if any).', '# Your project starts here.', '## Write-up')}
for s, t in enumerate(tmpl):
    if s in answer_or_code: continue
    a, b = src(new[s]), src(t)
    if a == b: continue
    extra = [l for l in difflib.ndiff(b.splitlines(), a.splitlines()) if l[:2] in ('+ ', '- ')]
    if s in (4, 21, 35) and all(('_DATA_DIR' in l or 'import os' in l or l.strip() in ('+', '-')) for l in extra):
        continue
    p.append(f'exam cell {s} changed: {extra[:4]}')
report(f'structure: 41 cells, types as in the template, {41 - len(answer_or_code)} exam cells unchanged (setup cells: data path only)', p)

# ---------------------------------------------------------------- 2. code
def statements(code):
    keep = []
    for l in code.splitlines():
        s = l.strip()
        if not s or s.startswith('#') or re.fullmatch(r"print\('\\n==== Section [\d.]+: .* ===='\)", s):
            continue
        keep.append(l.rstrip())
    return keep
p = []
for s in range(41):
    if new[s]['cell_type'] != 'code': continue
    want = [l for i in slots[s] for l in statements(src(old[i]))]
    got = statements(src(new[s]))
    if want != got:
        d = [l for l in difflib.unified_diff(want, got, lineterm='', n=0)][:6]
        p.append(f'slot {s}: {d}')
n_old = sum(len(statements(src(c))) for c in old if c['cell_type'] == 'code')
n_new = sum(len(statements(src(c))) for c in new if c['cell_type'] == 'code')
report(f'code: all {n_old} code lines of the 107 cells are in the 41 cells, in order and in the right slot ({n_new} found)', p)

# ---------------------------------------------------------------- 3. text
ens = {'_src': lambda i: src(old[i]), 're': re}
exec(bsrc[bsrc.index('EDITS = []'):bsrc.index('text = {i: src(i)')].replace('src(', '_src('), ens)
EDITS = ens['EDITS']
edited = {}
for i, o, n in EDITS:
    edited.setdefault(i, src(old[i]))
    edited[i] = edited[i].replace(o, n)
p, lines = [], ['# Text changes in the 41-cell version (generated by notes/final41/verify_final41.py)\n',
                'Every markdown difference between `Final_Autumn_2026-1.ipynb` and `Final_Autumn_2026_final.ipynb`, as a diff. '
                'Cells not listed are unchanged. Problem 3 notes (Sections 3.0-3.10) also had their headings demoted one '
                'level when they moved into the write-up cell as appendices; that change is not shown.\n']
all_new_md = '\n'.join(src(c) for c in new if c['cell_type'] == 'markdown')
demote = lambda t: re.sub(r'^(#{2,5}) ', lambda m: '#' + m.group(1) + ' ', t, flags=re.M)
for i, c in enumerate(old):
    if c['cell_type'] != 'markdown': continue
    target = edited.get(i, src(c))
    if i in {s[2] for s in P3}:
        target = demote(target)
    body = target.rstrip('\n')
    if body not in all_new_md:
        p.append(f'markdown cell {i} ({src(c)[:50]!r}) not found in the 41-cell notebook')
    if i in edited:
        d = list(difflib.unified_diff(src(c).splitlines(), edited[i].splitlines(), f'107-cell notebook, cell {i}', '41-cell notebook', lineterm='', n=0))
        lines.append(f'\n## Cell {i} of the 107-cell notebook\n\n```diff\n' + '\n'.join(d) + '\n```\n')
open('notes/final41/text_changes.md', 'w').write('\n'.join(lines))
n_md = sum(c['cell_type'] == 'markdown' for c in old)
report(f'text: all {n_md} markdown cells present; {len(edited)} cells carry the corrections (diffs in notes/final41/text_changes.md)', p)

# ---------------------------------------------------------------- 4. outputs
TIMING = re.compile(r'(\d+(?:\.\d+)?) ?(s|min|seconds)\b')
def norm_text(t):
    t = re.sub(r'\n?==== Section [\d.]+: .* ====\n', '\n', t)
    t = TIMING.sub('<time>', t)
    return t
def outputs(cells):
    text, imgs = [], []
    for c in cells:
        for o in c.get('outputs', []):
            if o['output_type'] == 'stream':
                text.append(o['text'] if isinstance(o['text'], str) else ''.join(o['text']))
            elif o['output_type'] in ('display_data', 'execute_result'):
                d = o['data']
                if 'image/png' in d:
                    imgs.append(hashlib.sha1(''.join(d['image/png']).encode()).hexdigest())
                if 'text/html' in d:
                    h = ''.join(d['text/html'])
                    text.append(re.sub(r'T_[0-9a-f]{5}', 'T_id', h))
                elif 'text/plain' in d and 'image/png' not in d:
                    text.append(''.join(d['text/plain']))
            elif o['output_type'] == 'error':
                text.append(f"ERROR {o.get('ename')}")
    return norm_text(''.join(text)), imgs
p, same_img, n_img = [], 0, 0
for s in range(41):
    if new[s]['cell_type'] != 'code': continue
    t_old, i_old = outputs([old[i] for i in slots[s]])
    t_new, i_new = outputs([new[s]])
    if t_old != t_new:
        a, b = t_old.splitlines(), t_new.splitlines()
        d = [l for l in difflib.unified_diff(a, b, lineterm='', n=0) if not l.startswith(('---', '+++', '@@'))]
        p.append(f'slot {s}: {len(d)} differing output lines, e.g. {d[:4]}')
    if len(i_old) != len(i_new):
        p.append(f'slot {s}: {len(i_old)} figures before, {len(i_new)} now')
    n_img += len(i_old)
    same_img += sum(a == b for a, b in zip(i_old, i_new))
report(f'outputs: printed text and tables identical slot by slot (timings excepted); figures: {n_img} before, '
       f'{sum(len(outputs([c])[1]) for c in new)} now, {same_img} byte-identical', p)

# ---------------------------------------------------------------- 5. numbers
def printed(cells):
    out = []
    for c in cells:
        for o in c.get('outputs', []):
            if o['output_type'] == 'stream':
                out.append(''.join(o['text']))
            elif o['output_type'] in ('execute_result', 'display_data'):
                for k in ('text/plain', 'text/html'):
                    if k in o['data']:
                        out.append(html.unescape(''.join(o['data'][k])))
    return '\n'.join(out).replace('−', '-')
SKIP = {str(k) for k in range(0, 13)} | {'300', '50', '168', '38', '400', '500', '1,000', '2,500', '2,499'}
def numbers(t):
    t = re.sub(r'\$[^$]*\$', ' ', t).replace('−', '-')
    return {n for n in re.findall(r'(?<![\w.])-?\d[\d,]*(?:\.\d+)?%?', t) if n not in SKIP and not re.fullmatch(r'\d{4}', n)}
def unprinted(cells, blob):
    miss = set()
    for c in cells:
        if c['cell_type'] != 'markdown' or not src(c).lstrip().startswith(('**Answer', '## Write-up')): continue
        for n in numbers(src(c)):
            core = n.lstrip('-')
            vs = {n, core, core.replace(',', ''), core.rstrip('%'), core.rstrip('%') + ' %'}
            if not any(v in blob for v in vs):
                miss.add(n)
    return miss
m_old = unprinted(old, printed(old) + '\n'.join(src(c) for c in old if c['cell_type'] == 'markdown' and not src(c).startswith(('**Answer', '## Write-up'))))
m_new = unprinted(new, printed(new) + '\n'.join(src(c) for c in new if c['cell_type'] == 'markdown' and not src(c).startswith(('**Answer', '## Write-up'))))
report(f'numbers: {len(m_new)} numbers in answers/write-up not found verbatim in any output (107-cell version: {len(m_old)}); '
       f'new ones: {sorted(m_new - m_old)}', sorted(m_new - m_old))
print('\nnumbers not found verbatim in either version (roundings, section numbers, lecture pages and similar):', sorted(m_new & m_old))
print('\nALL CHECKS PASSED' if ok else '\nSOME CHECKS FAILED')
sys.exit(0 if ok else 1)
